### ISSUE TITLE
Unity2022.3.6f1のプロジェクトで使用できない

### ISSUE THREAD

**Issue by amehuri** [c-colloid/PBReplacer-VPM#1]
VCCv2.2.2でUnity2022に移行したプロジェクトにPBReplacer1.4.1を入れましたが、ウィンドウを開くと何も表示されずConsoleに以下のエラーが出ます。

![image](https://github.com/c-colloid/PBReplacer-VPM/assets/110208161/b7e299b8-ab64-486d-b147-4f1baf89347e)
![image](https://github.com/c-colloid/PBReplacer-VPM/assets/110208161/3752ee25-b145-4a70-8536-bcc23bcc3005)

**Comment by c-colloid** [comment]
報告ありがとうございます
v1.5.0で修正対応しました
